class ValidateError(Exception):
    """Исключение при ошибки валидации."""